import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type React from "react";
import { AlertTriangle, ArrowDown, ArrowUp, CalendarDays, Camera, Check, ChevronRight, CircleStop, Clock3, ExternalLink, GripVertical, LocateFixed, MapPin, MessageCircle, Mic, Navigation, RefreshCw, Route, Send, Sparkles, SwitchCamera, Upload, Volume2, VolumeX, X } from "lucide-react";
import { agentSocketUrl, vantageApi } from "./api/client";
import type { AgentMessage, AgentServerEvent, ApprovalRequest, ApprovalResolution, DayRoute, RouteLeg } from "./types";
import "./agent-frame.css";
import "./agent-frame-revision.css";

type FrameView = "agent" | "itinerary" | "navigation";
type CameraState = "closed" | "opening" | "live" | "analyzing" | "failed";
export type VantageAgentFrameProps = { date?: string; initialRoute?: DayRoute; initialMessages?: AgentMessage[]; onOpenStop?: (taskId: string) => void; className?: string };

const today = () => new Date().toISOString().slice(0, 10);
const relativeFreshness = (value?: string) => value ? `Synced ${new Intl.RelativeTimeFormat(undefined,{numeric:"auto"}).format(Math.round((new Date(value).getTime()-Date.now())/60000),"minute")}` : "Not synced";
const reviewMode = (import.meta as ImportMeta & { env: { DEV: boolean } }).env.DEV && new URLSearchParams(location.search).get("review") === "agent-frame";
const reviewPhoto = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="700"><defs><linearGradient id="s" y2="1"><stop stop-color="#91b8d8"/><stop offset="1" stop-color="#e8d5ad"/></linearGradient></defs><rect width="1000" height="700" fill="url(#s)"/><path d="M0 490L160 360 290 450 470 280 650 440 820 330 1000 455V700H0Z" fill="#4c6246"/><rect x="190" y="315" width="620" height="285" fill="#eee2c7"/><path d="M140 340L500 120 860 340Z" fill="#344239"/><path d="M205 325L500 150 795 325Z" fill="#eef0e4"/><rect x="260" y="380" width="150" height="135" fill="#466474"/><rect x="590" y="380" width="150" height="135" fill="#466474"/><rect x="453" y="355" width="95" height="245" fill="#6f4932"/><rect y="580" width="1000" height="120" fill="#77935d"/><circle cx="860" cy="565" r="85" fill="#36533c"/><circle cx="100" cy="560" r="70" fill="#425f41"/></svg>`)}`;
const reviewRoute = ():DayRoute => ({date:today(),connectionStatus:"connected",calendarSyncedAt:new Date().toISOString(),routeGeneratedAt:new Date().toISOString(),stops:[
  {id:"review-stop-1",taskId:"review-task-1",stage:"QC",timeLabel:"9:30 AM",home:{id:"review-home-1",name:"Lakeview Lodge",unitCode:"LVL",address:"39420 Lake Drive, Big Bear Lake, CA"},place:{status:"validated",formattedAddress:"39420 Lake Drive, Big Bear Lake, CA",validatedAt:new Date().toISOString()}},
  {id:"review-stop-2",taskId:"review-task-2",stage:"Onboarding",timeLabel:"11:15 AM",home:{id:"review-home-2",name:"Juniper House",unitCode:"JNH",address:"42562 Juniper Drive, Big Bear Lake, CA"},place:{status:"validated",formattedAddress:"42562 Juniper Drive, Big Bear Lake, CA",validatedAt:new Date().toISOString()}},
  {id:"review-stop-3",taskId:"review-task-3",stage:"Turnover",timeLabel:"1:40 PM",home:{id:"review-home-3",name:"Moonridge A-Frame",unitCode:"MAF",address:"43108 Moonridge Road, Big Bear Lake, CA"},place:{status:"stale",formattedAddress:"43108 Moonridge Road, Big Bear Lake, CA"}}
],legs:[
  {id:"review-leg-1",fromLabel:"Current location",toLabel:"Lakeview Lodge",distanceText:"4.8 mi",durationText:"12 min",eta:"9:24 AM",trafficAware:true,googleMapsUrl:"https://www.google.com/maps/dir/?api=1&destination=39420+Lake+Drive+Big+Bear+Lake+CA",steps:[{id:"s1",instruction:"Turn right onto Big Bear Boulevard",distanceText:"600 ft",durationText:"1 min"},{id:"s1b",instruction:"Keep left at the lake toward Boulder Bay",distanceText:"2.1 mi",durationText:"5 min"},{id:"s1c",instruction:"Turn left onto Lake Drive",distanceText:"0.3 mi",durationText:"2 min"}]},
  {id:"review-leg-2",fromLabel:"Lakeview Lodge",toLabel:"Juniper House",distanceText:"6.2 mi",durationText:"17 min",eta:"11:08 AM",trafficAware:true,googleMapsUrl:"https://www.google.com/maps/dir/?api=1",steps:[{id:"s2",instruction:"Continue east on Lakeview Drive",distanceText:"1.2 mi"}]},
  {id:"review-leg-3",fromLabel:"Juniper House",toLabel:"Moonridge A-Frame",distanceText:"3.1 mi",durationText:"9 min",eta:"1:34 PM",trafficAware:true,googleMapsUrl:"https://www.google.com/maps/dir/?api=1",steps:[{id:"s3",instruction:"Bear left toward Moonridge Road",distanceText:"0.4 mi"}]}
]});
const reviewApproval = (status:ApprovalRequest["status"]="pending",preview:"loaded"|"loading"|"failed"="loaded"):ApprovalRequest => ({approvalId:"review-approval",inspectionId:"review-inspection",itemId:"kitchen-refrigerator",destinationLabel:"Kitchen · Refrigerator cold and clean",proposedVerdict:"PASS",rationale:"Shelves are clear, interior surfaces look clean, and the temperature display is visible.",mediaId:"review-media",mediaUrl:preview==="loaded"?reviewPhoto:preview==="failed"?"data:image/png;base64,invalid-review-fixture":undefined,error:preview==="failed"?"The original preview could not be loaded.":undefined,status,expiresAt:new Date(Date.now()+600000).toISOString()});

export function VantageAgentFrame({ date=today(), initialRoute, initialMessages=[], onOpenStop, className="" }: VantageAgentFrameProps) {
  const seededRoute=reviewMode?reviewRoute():initialRoute;
  const [view,setView]=useState<FrameView>("agent"), [route,setRoute]=useState<DayRoute|undefined>(seededRoute), [routeError,setRouteError]=useState<string>(), [routeLoading,setRouteLoading]=useState(!seededRoute);
  const [messages,setMessages]=useState<AgentMessage[]>(initialMessages), [draft,setDraft]=useState(""), [voiceInput,setVoiceInput]=useState(false), [voiceOutput,setVoiceOutput]=useState(true);
  const [connected,setConnected]=useState(false), [socketError,setSocketError]=useState<string>(), [approval,setApproval]=useState<ApprovalRequest>(), [feedback,setFeedback]=useState(""), [feedbackMode,setFeedbackMode]=useState<"text"|"voice">("text");
  const [cameraState,setCameraState]=useState<CameraState>("closed"), [cameraError,setCameraError]=useState<string>();
  const [legIndex,setLegIndex]=useState(0),[stepIndex,setStepIndex]=useState(0),[navigationState,setNavigationState]=useState<"locating"|"active"|"rerouting"|"arrived"|"error">("locating"),[navigationMessage,setNavigationMessage]=useState<string>();
  const socketRef=useRef<WebSocket|undefined>(undefined), videoRef=useRef<HTMLVideoElement>(null), streamRef=useRef<MediaStream|undefined>(undefined), recognitionRef=useRef<{stop:()=>void}|undefined>(undefined);
  const cameraStatusRef=useRef<HTMLDivElement>(null), approvalRef=useRef<HTMLElement>(null);
  const activeLeg=route?.legs[legIndex], nextStop=route?.stops[legIndex];

  const loadRoute=useCallback(async()=>{setRouteLoading(true);setRouteError(undefined);const result=await vantageApi.dayRoute(date);if(result.ok)setRoute(result.data);else setRouteError(result.error.message);setRouteLoading(false)},[date]);
  useEffect(()=>{if(!seededRoute)void loadRoute()},[seededRoute,loadRoute]);
  useEffect(()=>{if(reviewMode){setConnected(true);return}let disposed=false;vantageApi.wsToken().then(result=>{if(disposed||!result.ok){if(!result.ok)setSocketError(result.error.message);return}const ws=new WebSocket(agentSocketUrl(result.data.token));socketRef.current=ws;ws.onopen=()=>{setConnected(true);setSocketError(undefined)};ws.onclose=()=>{setConnected(false);setApproval(a=>a&&["pending","resolving","reshoot"].includes(a.status)?{...a,status:"disconnected"}:a)};ws.onerror=()=>setSocketError("The live agent connection is unavailable.");ws.onmessage=e=>{try{handleServerEvent(JSON.parse(e.data) as AgentServerEvent)}catch{setSocketError("Vantage received an unreadable live update.")}}});return()=>{disposed=true;socketRef.current?.close()}},[]);
  useEffect(()=>{if(cameraState==="failed")cameraStatusRef.current?.focus()},[cameraState]);
  useEffect(()=>{if(approval)approvalRef.current?.focus()},[approval?.approvalId,approval?.status]);
  function handleServerEvent(event:AgentServerEvent){
    if(event.type==="agent_message")setMessages(m=>[...m,event]);
    if(event.type==="approval_requested")setApproval({...event,destinationLabel:event.destinationLabel||event.itemLabel||event.assetLabel||"Unresolved destination",status:"pending"});
    if(event.type==="approval_completed"){setApproval(a=>a?.approvalId===event.approvalId?{...a,status:"approved"}:a);setMessages(m=>[...m,{id:crypto.randomUUID(),role:"agent",text:event.message||"Approved. I attached the original to the correct inspection item.",createdAt:new Date().toISOString()}])}
    if(event.type==="approval_expired"||event.type==="approval_cancelled")setApproval(a=>a?.approvalId===event.approvalId?{...a,status:event.type==="approval_expired"?"expired":"cancelled",error:event.message}:a);
    if(event.type==="approval_resumed")setApproval(a=>a?.approvalId===event.approvalId?{...a,status:"resumed"}:a);
    if(event.type==="camera_requested"){void openCamera();setMessages(m=>[...m,{id:crypto.randomUUID(),role:"agent",text:event.instruction,createdAt:new Date().toISOString()}])}
    if(event.type==="bidi_transcript_stream"&&(event.text||event.transcript)&&event.isFinal!==false)setMessages(m=>[...m,{id:crypto.randomUUID(),role:event.role==="user"?"user":"agent",text:(event.text||event.transcript)!,createdAt:new Date().toISOString()}]);
    if(event.type==="navigation_progress"){setLegIndex(event.legIndex);setStepIndex(event.stepIndex);setNavigationState(event.state||"active");setNavigationMessage(event.message)}
  }
  const sendSocket=(payload:unknown)=>{if(reviewMode)return true;const socket=socketRef.current;if(!socket||socket.readyState!==WebSocket.OPEN){setSocketError("Reconnect to Vantage before sending this update.");return false}socket.send(JSON.stringify(payload));return true};
  function submitMessage(text=draft){const clean=text.trim();if(!clean)return;if(sendSocket({type:"user_message",text:clean,inputMode:voiceInput?"voice":"text"})){setMessages(m=>[...m,{id:crypto.randomUUID(),role:"user",text:clean,createdAt:new Date().toISOString()}]);setDraft("")}}
  function resolveApproval(resolution:ApprovalResolution){if(!approval)return;if(sendSocket({type:"approval_resolved",...resolution})){setApproval({...approval,status:"resolving"});setFeedback("")}}
  async function openCamera(){if(view==="navigation")setView("agent");setCameraState("opening");setCameraError(undefined);try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraState("live")}catch(e){setCameraState("failed");setCameraError(e instanceof Error?e.message:"Camera permission is unavailable.")}}
  function closeCamera(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=undefined;setCameraState("closed")}
  async function flipCamera(){const current=streamRef.current?.getVideoTracks()[0]?.getSettings().facingMode;closeCamera();setCameraState("opening");try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:current==="user"?"environment":"user"}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraState("live")}catch(e){setCameraState("failed");setCameraError(e instanceof Error?e.message:"Could not switch camera.")}}
  function capture(){if(!videoRef.current||cameraState!=="live")return;const video=videoRef.current,canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob){setCameraError("The camera did not produce an image.");return}setCameraState("analyzing");const reader=new FileReader();reader.onload=()=>{if(!sendSocket({type:"camera_capture",mimeType:blob.type,dataUrl:reader.result})){setCameraState("failed");return}closeCamera()};reader.readAsDataURL(blob)},"image/jpeg",0.96)}
  function submitOriginal(file?:File){if(!file)return;setCameraState("analyzing");const reader=new FileReader();reader.onerror=()=>{setCameraState("failed");setCameraError("The selected original could not be read.")};reader.onload=()=>{if(sendSocket({type:"camera_capture",mimeType:file.type,dataUrl:reader.result,filename:file.name}))closeCamera();else setCameraState("failed")};reader.readAsDataURL(file)}
  function toggleDictation(target:"message"|"feedback") {const Recognition=(window as unknown as {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>any}).webkitSpeechRecognition;if(!Recognition){setSocketError("Voice input is not supported by this browser.");return}if(recognitionRef.current){recognitionRef.current.stop();recognitionRef.current=undefined;setVoiceInput(false);return}const recognition=new Recognition();recognition.continuous=false;recognition.interimResults=false;recognition.onresult=(event:any)=>{const text=event.results[0][0].transcript;if(target==="feedback")setFeedback(text);else setDraft(text)};recognition.onend=()=>{recognitionRef.current=undefined;setVoiceInput(false)};recognitionRef.current=recognition;setVoiceInput(true);recognition.start()}
  const statusLabel=connected?"Live agent connected":socketError||"Reconnecting to live agent";

  return <main className={`va-frame ${cameraState!=="closed"?"va-frame--camera":""} ${className}`}>
    <section className="va-agent" aria-label="Vantage agent">
      <header className="va-agent__header"><button className="va-brand" onClick={()=>setView("agent")} aria-label="Return to agent"><span className="va-orb" aria-hidden="true"/><span><strong>Vantage</strong><small>{statusLabel}</small></span></button><div className="va-mode-actions"><button className={voiceOutput?"is-active":""} onClick={()=>setVoiceOutput(v=>!v)} aria-label={voiceOutput?"Mute agent voice":"Enable agent voice"}>{voiceOutput?<Volume2/>:<VolumeX/>}</button><button onClick={()=>void openCamera()} aria-label="Open camera"><Camera/></button></div></header>
      <div className="va-camera" aria-hidden={cameraState==="closed"} aria-busy={cameraState==="opening"||cameraState==="analyzing"}><video ref={videoRef} playsInline muted aria-label="Live rear camera preview"/><div className="va-camera__shade"/><div className="va-camera__top"><span role="status" aria-live="polite"><LocateFixed/> {cameraState==="analyzing"?"Vantage is analyzing the original":cameraState==="opening"?"Opening camera":"Lens active"}</span><button onClick={closeCamera} aria-label="Close camera"><X/></button></div>{cameraState==="failed"?<div ref={cameraStatusRef} tabIndex={-1} className="va-camera__error" role="alert"><AlertTriangle/><strong>Camera unavailable</strong><p>{cameraError}</p><div><button onClick={()=>void openCamera()}>Try camera again</button><label className="va-upload"><Upload/>Choose original<input type="file" accept="image/*" capture="environment" onChange={e=>submitOriginal(e.target.files?.[0])}/></label><button onClick={closeCamera}>Continue without camera</button></div></div>:<div className="va-camera__controls"><button onClick={()=>void flipCamera()} aria-label="Switch camera"><SwitchCamera/></button><button className="va-shutter" disabled={cameraState!=="live"} onClick={capture} aria-label={cameraState==="live"?"Take photo":"Camera is not ready"}><span/></button><button onClick={closeCamera} aria-label="Stop camera"><CircleStop/></button></div>}</div>
      <div className="va-conversation"><div className="va-agent-prompt"><span className="va-orb va-orb--small"/><div><small>Vantage agent</small><p>{nextStop?`Your next Calendar stop is ${nextStop.home.name}. ${activeLeg?`${activeLeg.durationText} away.`:"I’m building the route now."}`:"I’m ready to help with today’s field work."}</p></div></div>{messages.slice(-3).map(message=><div key={message.id} className={`va-message va-message--${message.role}`}><small>{message.role==="user"?"You":"Vantage"}</small><p>{message.text}</p></div>)}</div>
      {approval&&<ApprovalPanel panelRef={approvalRef} approval={approval} feedback={feedback} setFeedback={setFeedback} feedbackMode={feedbackMode} setFeedbackMode={setFeedbackMode} onApprove={()=>resolveApproval({approvalId:approval.approvalId,decision:"approve"})} onTakeAgain={()=>setApproval({...approval,status:"reshoot"})} onSubmitFeedback={()=>resolveApproval({approvalId:approval.approvalId,decision:"reshoot",feedback,inputMode:feedbackMode})} onVoice={()=>toggleDictation("feedback")}/>} 
      {!approval&&<NextStopCard route={route} loading={routeLoading} error={routeError} onRetry={loadRoute} onNavigate={()=>setView("navigation")} onItinerary={()=>setView("itinerary")}/>} 
      <footer className="va-composer"><button className={voiceInput?"is-recording":""} onClick={()=>toggleDictation("message")} aria-label={voiceInput?"Stop voice input":"Speak to Vantage"}><Mic/></button><label><span className="sr-only">Message Vantage</span><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submitMessage()}} placeholder="Ask Vantage anything…"/></label><button onClick={()=>submitMessage()} disabled={!draft.trim()} aria-label="Send message"><Send/></button></footer>
    </section>
    {view==="agent"&&<DesktopDayPanel route={route} onItinerary={()=>setView("itinerary")} onNavigate={()=>setView("navigation")}/>} 
    {view==="itinerary"&&<PersistentItinerary route={route} loading={routeLoading} error={routeError} draft={draft} setDraft={setDraft} onSubmit={()=>submitMessage()} onVoice={()=>toggleDictation("message")} voiceActive={voiceInput} connected={connected} onClose={()=>setView("agent")} onRefresh={async()=>{if(reviewMode){setRoute(reviewRoute());return}const r=await vantageApi.syncCalendar();if(r.ok)void loadRoute();else setRouteError(r.error.message)}} onReorder={async(ids)=>{if(reviewMode){setRoute(r=>r?{...r,stops:ids.map(id=>r.stops.find(s=>s.taskId===id)!).filter(Boolean)}:r);return}const result=await vantageApi.reorderDayRoute(ids);if(result.ok)setRoute(result.data);else setRouteError(result.error.message)}} onNavigate={()=>{setNavigationState("locating");setView("navigation")}} onOpenStop={onOpenStop}/>} 
    {view==="navigation"&&activeLeg&&<ProgressNavigation leg={activeLeg} legIndex={legIndex} legCount={route?.legs.length||1} stepIndex={stepIndex} navigationState={navigationState} navigationMessage={navigationMessage} nextLabel={nextStop?.home.name||activeLeg.toLabel} connected={connected} draft={draft} setDraft={setDraft} onSubmit={()=>submitMessage()} onVoice={()=>toggleDictation("message")} voiceActive={voiceInput} onClose={()=>setView("agent")}/>} 
    {reviewMode&&<ReviewHarnessV2 onView={setView} onCamera={v=>{if(v!=="closed"&&view==="navigation")setView("agent");setCameraState(v)}} onApproval={setApproval} onProgress={(leg:number,step:number,state:"locating"|"active"|"rerouting"|"arrived"|"error")=>{setLegIndex(leg);setStepIndex(step);setNavigationState(state);setView("navigation")}} route={route}/>} 
    <div className="sr-only" role="status" aria-live="polite">{approval?`Approval ${approval.status} for ${approval.destinationLabel}`:statusLabel}</div>
  </main>
}

function NextStopCard({route,loading,error,onRetry,onNavigate,onItinerary}:{route?:DayRoute;loading:boolean;error?:string;onRetry:()=>void;onNavigate:()=>void;onItinerary:()=>void}){const stop=route?.stops[0],leg=route?.legs[0];if(loading)return <section className="va-next va-next--loading" aria-busy="true"><span/><span/><span/></section>;if(error)return <section className="va-next va-next--error" role="alert"><AlertTriangle/><div><strong>Route unavailable</strong><p>{error}</p></div><button onClick={onRetry}><RefreshCw/>Retry</button></section>;if(!stop)return <section className="va-next"><CalendarDays/><div><small>Google Calendar</small><strong>No more linked stops today</strong></div><button onClick={onItinerary}>View day</button></section>;return <section className="va-next"><div className="va-next__eyebrow"><span><CalendarDays/>Next calendar stop · {stop.timeLabel||"Today"}</span><button onClick={onItinerary}>Full day <ChevronRight/></button></div><h2>{stop.home.name}</h2><p><MapPin/>{stop.place?.formattedAddress||stop.home.address}</p><div className="va-route-line"><div><Route/><span><strong>{leg?.durationText||"—"}</strong><small>{leg?.distanceText||"Route calculating"}</small></span></div><div><Clock3/><span><strong>{leg?.eta||"—"}</strong><small>arrival</small></span></div><button onClick={onNavigate} disabled={!leg}><Navigation/>Navigate</button></div><div className="va-freshness"><span className={`va-place va-place--${stop.place?.status||"unverified"}`}><Check/>{stop.place?.status==="validated"?"Places verified":stop.place?.status==="stale"?"Places check stale":"Address unverified"}</span><span>{relativeFreshness(route?.calendarSyncedAt)}</span></div></section>}

function ApprovalPanel({panelRef,approval,feedback,setFeedback,feedbackMode,setFeedbackMode,onApprove,onTakeAgain,onSubmitFeedback,onVoice}:{panelRef:React.RefObject<HTMLElement|null>;approval:ApprovalRequest;feedback:string;setFeedback:(s:string)=>void;feedbackMode:"text"|"voice";setFeedbackMode:(v:"text"|"voice")=>void;onApprove:()=>void;onTakeAgain:()=>void;onSubmitFeedback:()=>void;onVoice:()=>void}){const blocked=["resolving","approved","expired","cancelled","disconnected","upload_failed"].includes(approval.status);return <section ref={panelRef} tabIndex={-1} className={`va-approval va-approval--${approval.status}`} aria-label={`Photo approval for ${approval.destinationLabel}`}><div className="va-approval__destination"><span><Sparkles/>Proposed evidence</span><strong>{approval.destinationLabel}</strong></div>{approval.mediaUrl?<img src={approval.mediaUrl} alt={`Proposed evidence for ${approval.destinationLabel}`}/>:<div className="va-media-pending" role="status"><Camera/><span>Original preview is loading</span></div>}<div className="va-approval__copy"><div><span className="va-verdict">{approval.proposedVerdict||"REVIEW"}</span><h2>{approval.status==="approved"?"Shot approved":approval.status==="reshoot"?"Let’s give it another shot":approval.status==="resolving"?"Saving your decision…":"Here’s my best shot"}</h2></div><p>{approval.rationale}</p></div>{approval.status==="reshoot"?<div className="va-feedback"><h3>Tell Vantage what to change</h3><p>Speak or type a quick note. Your instruction becomes the next capture guidance.</p><div className="va-feedback__modes"><button className={feedbackMode==="voice"?"active":""} onClick={()=>{setFeedbackMode("voice");onVoice()}}><Mic/>Voice</button><button className={feedbackMode==="text"?"active":""} onClick={()=>setFeedbackMode("text")}><MessageCircle/>Type</button></div><textarea autoFocus value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Get closer and show the model plate clearly…"/><button className="va-primary" disabled={!feedback.trim()} onClick={onSubmitFeedback}>Send capture instruction <Send/></button></div>:blocked?<ApprovalState approval={approval}/>:<div className="va-approval__actions"><button onClick={onTakeAgain}>Take Again</button><button className="va-primary" onClick={onApprove}><Check/>Approve</button></div>}</section>}
function ApprovalState({approval}:{approval:ApprovalRequest}){const map:Record<string,[typeof Check,string,string]>={resolving:[RefreshCw,"Approval pending","Waiting for the server to attach the original."],approved:[Check,"Approved and attached","The server confirmed the exact destination."],expired:[Clock3,"Approval expired","Ask Vantage to propose the photo again."],cancelled:[X,"Approval cancelled","No evidence was attached."],disconnected:[AlertTriangle,"Connection interrupted","Your pending decision is preserved and will resume after reconnection."],upload_failed:[AlertTriangle,"Original upload failed","The asset is not complete. Retry the upload before approval."]};const [Icon,title,copy]=map[approval.status]||[RefreshCw,"Approval resumed","Review the proposed original before continuing."];return <div className="va-approval-state" role={approval.status==="upload_failed"?"alert":"status"}><Icon/><div><strong>{title}</strong><p>{approval.error||copy}</p></div></div>}

function Itinerary({route,loading,error,onClose,onRefresh,onReorder,onNavigate,onOpenStop}:{route?:DayRoute;loading:boolean;error?:string;onClose:()=>void;onRefresh:()=>void;onReorder:(ids:string[])=>void;onNavigate:()=>void;onOpenStop?:(id:string)=>void}){const move=(index:number,delta:number)=>{if(!route)return;const ids=route.stops.map(s=>s.taskId),to=index+delta;if(to<0||to>=ids.length)return;[ids[index],ids[to]]=[ids[to],ids[index]];onReorder(ids)};return <section className="va-sheet" aria-label="Today’s itinerary"><header><div><small>Calendar-backed itinerary</small><h1>My Day</h1></div><button onClick={onClose} aria-label="Close itinerary"><X/></button></header><div className="va-sync"><CalendarDays/><div><strong>Google Calendar</strong><span>{route?.connectionStatus||"Checking"} · {relativeFreshness(route?.calendarSyncedAt)}</span></div><button onClick={onRefresh}><RefreshCw/>Refresh</button></div>{loading?<p>Building today’s route…</p>:error?<p role="alert">{error}</p>:<><p className="va-reorder-help"><GripVertical/> Reorder stops and Vantage will refresh the remaining route.</p><ol className="va-itinerary">{route?.stops.map((stop,index)=><li key={stop.id}><span>{String(index+1).padStart(2,"0")}</span><button onClick={()=>onOpenStop?.(stop.taskId)}><small>{stop.timeLabel||stop.startAt||"Scheduled"}</small><strong>{stop.home.name}</strong><p>{stop.home.address}</p><em className={`va-place va-place--${stop.place?.status||"unverified"}`}>{stop.place?.status==="validated"?"Places verified":"Needs address review"}</em></button><div className="va-reorder"><button disabled={index===0} onClick={()=>move(index,-1)} aria-label={`Move ${stop.home.name} earlier`}><ArrowUp/></button><button disabled={index===route.stops.length-1} onClick={()=>move(index,1)} aria-label={`Move ${stop.home.name} later`}><ArrowDown/></button></div></li>)}</ol></>}<button className="va-primary va-sheet__nav" disabled={!route?.legs.length} onClick={onNavigate}><Navigation/>Start navigation</button></section>}
function NavigationView({leg,nextLabel,draft,setDraft,onSubmit,onVoice,voiceActive,onClose}:{leg:RouteLeg;nextLabel:string;draft:string;setDraft:(s:string)=>void;onSubmit:()=>void;onVoice:()=>void;voiceActive:boolean;onClose:()=>void}){const step=leg.steps[0];return <section className="va-nav-view" aria-label="Active navigation"><header><button onClick={onClose} aria-label="Close navigation"><ArrowDown/></button><div><small>Driving to</small><strong>{nextLabel}</strong></div><a href={leg.googleMapsUrl} target="_blank" rel="noreferrer">Google Maps <ExternalLink/></a></header><div className="va-map" aria-label="Route overview"><div className="va-road va-road--one"/><div className="va-road va-road--two"/><span className="va-map__current"><Navigation/></span><span className="va-map__destination"><MapPin/></span></div><div className="va-turn"><span>{step?.distanceText||leg.distanceText}</span><div><Navigation/><h1>{step?.instruction||`Continue to ${leg.toLabel}`}</h1></div><p>Then continue toward {leg.toLabel}</p></div><footer><div className="va-nav-eta"><strong>{leg.eta}</strong><small>{leg.durationText} · {leg.distanceText}</small></div><span className="va-orb va-orb--small"/><button className={voiceActive?"is-recording":""} onClick={onVoice} aria-label={voiceActive?"Stop voice input":"Speak to Vantage"}><Mic/></button><label><span className="sr-only">Message Vantage while navigating</span><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")onSubmit()}} placeholder="Message Vantage…"/></label><button onClick={onSubmit} disabled={!draft.trim()} aria-label="Send message to Vantage"><Send/></button></footer></section>}

function DesktopDayPanel({route,onItinerary,onNavigate}:{route?:DayRoute;onItinerary:()=>void;onNavigate:()=>void}){const leg=route?.legs[0],stop=route?.stops[0];return <aside className="va-desktop-day" aria-label="Today’s route overview"><header><div><small>Field command</small><h1>Today, at a glance</h1></div><button onClick={onItinerary}>Manage route <ChevronRight/></button></header><div className="va-desktop-map"><div className="va-road va-road--one"/><div className="va-road va-road--two"/>{route?.stops.map((s,i)=><span key={s.id} className={`va-map-stop va-map-stop--${i+1}`}>{i+1}</span>)}</div>{stop&&leg?<section className="va-desktop-leg"><small>Next calendar stop</small><h2>{stop.home.name}</h2><p><MapPin/>{stop.home.address}</p><div><strong>{leg.durationText}</strong><span>{leg.distanceText} · arrive {leg.eta}</span></div><button className="va-primary" onClick={onNavigate}><Navigation/>Start turn-by-turn</button></section>:<section className="va-desktop-leg"><h2>Route context appears here</h2><p>Connect Calendar and validate property addresses to build today’s route.</p></section>}<ol>{route?.stops.map((s,i)=><li key={s.id}><span>{i+1}</span><div><strong>{s.home.name}</strong><small>{s.timeLabel} · {s.stage}</small></div><em className={`va-place va-place--${s.place?.status||"unverified"}`}>{s.place?.status==="validated"?"Verified":"Review"}</em></li>)}</ol></aside>}

function ReviewHarness({onView,onCamera,onApproval}:{onView:(v:FrameView)=>void;onCamera:(v:CameraState)=>void;onApproval:(v:ApprovalRequest|undefined)=>void}){return <nav className="va-review" aria-label="Development review states"><strong>DEV REVIEW</strong><button onClick={()=>onView("agent")}>Agent</button><button onClick={()=>onView("itinerary")}>Itinerary</button><button onClick={()=>onView("navigation")}>Navigation</button><button onClick={()=>onCamera("opening")}>Camera opening</button><button onClick={()=>onCamera("failed")}>Camera denied</button><button onClick={()=>onApproval(reviewApproval("pending"))}>Proposed</button><button onClick={()=>onApproval(reviewApproval("reshoot"))}>Take again</button>{(["resolving","approved","expired","disconnected","upload_failed","resumed"] as ApprovalRequest["status"][]).map(s=><button key={s} onClick={()=>onApproval(reviewApproval(s))}>{s}</button>)}<button onClick={()=>onApproval(undefined)}>Clear</button></nav>}

type AgentDockProps={draft:string;setDraft:(s:string)=>void;onSubmit:()=>void;onVoice:()=>void;voiceActive:boolean;connected:boolean};
function CompactAgentDock({draft,setDraft,onSubmit,onVoice,voiceActive,connected}:AgentDockProps){return <div className="va-compact-agent"><div><span className="va-orb va-orb--small"/><span><strong>Vantage</strong><small>{connected?"Live agent connected":"Agent reconnecting"}</small></span></div><button className={voiceActive?"is-recording":""} onClick={onVoice} aria-label={voiceActive?"Stop voice input":"Speak to Vantage"}><Mic/></button><label><span className="sr-only">Message Vantage</span><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")onSubmit()}} placeholder="Message Vantage…"/></label><button onClick={onSubmit} disabled={!draft.trim()} aria-label="Send message"><Send/></button></div>}

function PersistentItinerary({route,loading,error,draft,setDraft,onSubmit,onVoice,voiceActive,connected,onClose,onRefresh,onReorder,onNavigate,onOpenStop}:AgentDockProps&{route?:DayRoute;loading:boolean;error?:string;onClose:()=>void;onRefresh:()=>void;onReorder:(ids:string[])=>void;onNavigate:()=>void;onOpenStop?:(id:string)=>void}){const move=(index:number,delta:number)=>{if(!route)return;const ids=route.stops.map(s=>s.taskId),target=index+delta;if(target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target],ids[index]];onReorder(ids)};return <section className="va-sheet va-sheet--persistent" aria-label="Today’s itinerary"><CompactAgentDock {...{draft,setDraft,onSubmit,onVoice,voiceActive,connected}}/><header><div><small>Calendar-backed itinerary</small><h1>My Day</h1></div><button onClick={onClose} aria-label="Close itinerary"><X/></button></header><div className="va-sync"><CalendarDays/><div><strong>Google Calendar</strong><span>{route?.connectionStatus||"Checking"} · {relativeFreshness(route?.calendarSyncedAt)}</span></div><button onClick={onRefresh}><RefreshCw/>Refresh</button></div>{loading?<p role="status">Building today’s route…</p>:error?<p role="alert">{error}</p>:<><p className="va-reorder-help"><GripVertical/>Reorder stops to refresh remaining route.</p><ol className="va-itinerary">{route?.stops.map((stop,index)=><li key={stop.id}><span>{String(index+1).padStart(2,"0")}</span><button onClick={()=>onOpenStop?.(stop.taskId)}><small>{stop.timeLabel||"Scheduled"}</small><strong>{stop.home.name}</strong><p>{stop.home.address}</p><em className={`va-place va-place--${stop.place?.status||"unverified"}`}>{stop.place?.status==="validated"?"Places verified":"Needs address review"}</em></button><div className="va-reorder"><button disabled={index===0} onClick={()=>move(index,-1)} aria-label={`Move ${stop.home.name} earlier`}><ArrowUp/></button><button disabled={index===(route?.stops.length||0)-1} onClick={()=>move(index,1)} aria-label={`Move ${stop.home.name} later`}><ArrowDown/></button></div></li>)}</ol></>}<button className="va-primary va-sheet__nav" disabled={!route?.legs.length} onClick={onNavigate}><Navigation/>Start navigation</button></section>}

function ProgressNavigation({leg,legIndex,legCount,stepIndex,navigationState,navigationMessage,nextLabel,connected,...dock}:AgentDockProps&{leg:RouteLeg;legIndex:number;legCount:number;stepIndex:number;navigationState:"locating"|"active"|"rerouting"|"arrived"|"error";navigationMessage?:string;nextLabel:string;onClose:()=>void}){const step=leg.steps[Math.min(stepIndex,Math.max(0,leg.steps.length-1))],following=leg.steps[stepIndex+1];return <section className="va-nav-view va-nav-view--progress" aria-label="Active navigation"><CompactAgentDock {...dock} connected={connected}/><header><button onClick={dock.onClose} aria-label="Close navigation"><ArrowDown/></button><div><small>Leg {legIndex+1} of {legCount} · driving to</small><strong>{nextLabel}</strong></div><a href={leg.googleMapsUrl} target="_blank" rel="noreferrer">Google Maps <ExternalLink/></a></header><div className="va-map" aria-label="Google route summary"><div className="va-route-polyline"/><span className="va-map__current"><Navigation/></span><span className="va-map__destination"><MapPin/></span><p>Google route path · traffic-aware</p></div><div className={`va-nav-status va-nav-status--${navigationState}`} role={navigationState==="error"?"alert":"status"}><LocateFixed/><strong>{navigationState==="locating"?"Finding your current location":navigationState==="rerouting"?"Rerouting":navigationState==="arrived"?`Arrived at ${nextLabel}`:navigationState==="error"?"Navigation interrupted":"On route"}</strong><span>{navigationMessage||(!connected?"Reconnect to refresh location and traffic.":navigationState==="arrived"&&legIndex+1<legCount?"Next house is ready to start.":"Location and ETA update from the active route session.")}</span></div><div className="va-turn"><span>{step?.distanceText||leg.distanceText}</span><div><Navigation/><h1>{step?.instruction||`Continue to ${leg.toLabel}`}</h1></div><p>{following?`Then ${following.instruction} in ${following.distanceText}`:`Continue to ${leg.toLabel}`}</p><ol className="va-step-list" aria-label="Remaining maneuvers">{leg.steps.slice(stepIndex).map((s,i)=><li key={s.id} aria-current={i===0?"step":undefined}><span>{i===0?"Now":`Then ${i}`}</span><strong>{s.instruction}</strong><small>{s.distanceText}</small></li>)}</ol></div><footer><div className="va-nav-eta"><strong>{leg.eta}</strong><small>{leg.durationText} · {leg.distanceText}</small></div></footer></section>}

function ReviewHarnessV2({onView,onCamera,onApproval,onProgress,route}:{onView:(v:FrameView)=>void;onCamera:(v:CameraState)=>void;onApproval:(v:ApprovalRequest|undefined)=>void;onProgress:(leg:number,step:number,state:"locating"|"active"|"rerouting"|"arrived"|"error")=>void;route?:DayRoute}){const [open,setOpen]=useState(false),[leg,setLeg]=useState(0),[step,setStep]=useState(0);const progress=(dl:number,ds:number,state:"locating"|"active"|"rerouting"|"arrived"|"error"="active")=>{let nextLeg=Math.max(0,Math.min((route?.legs.length||1)-1,leg+dl)),nextStep=dl?0:Math.max(0,Math.min((route?.legs[nextLeg]?.steps.length||1)-1,step+ds));setLeg(nextLeg);setStep(nextStep);onProgress(nextLeg,nextStep,state)};return <aside className={`va-review-v2 ${open?"is-open":""}`}><button className="va-review-toggle" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>DEV {open?"Close":"States"}</button>{open&&<nav aria-label="Development review states"><button onClick={()=>onView("agent")}>Agent</button><button onClick={()=>onView("itinerary")}>Itinerary</button><button onClick={()=>progress(0,0,"locating")}>Navigate</button><button onClick={()=>progress(0,1)}>Next step</button><button onClick={()=>progress(0,-1)}>Previous</button><button onClick={()=>progress(1,0,"active")}>Next house</button><button onClick={()=>progress(0,0,"rerouting")}>Reroute</button><button onClick={()=>progress(0,0,"error")}>Nav error</button><button onClick={()=>progress(0,0,"arrived")}>Arrived</button><button onClick={()=>onCamera("opening")}>Camera</button><button onClick={()=>onCamera("failed")}>Denied</button><button onClick={()=>onApproval(reviewApproval("pending"))}>Photo</button><button onClick={()=>onApproval(reviewApproval("pending","loading"))}>Loading</button><button onClick={()=>onApproval(reviewApproval("pending","failed"))}>Bad preview</button><button onClick={()=>onApproval(reviewApproval("reshoot"))}>Retake</button>{(["resolving","approved","expired","disconnected","upload_failed","resumed"] as ApprovalRequest["status"][]).map(s=><button key={s} onClick={()=>onApproval(reviewApproval(s))}>{s}</button>)}<button onClick={()=>onApproval(undefined)}>Clear</button></nav>}</aside>}
