import { useCallback, useEffect, useState } from "react";
import { Building2, ClipboardList, FileText, UserRound } from "lucide-react";
import { MagicCodeSignIn, OrganizationChooser } from "./screens/AuthScreens";
import { MyDay, Properties, PropertySheet } from "./screens/CoreScreens";
import { OnboardingCanvas, InventoryReview } from "./screens/Onboarding";
import { DigitalTwin, Profile, Reports, TurnoverConsole } from "./screens/Operations";
import { PageState } from "./components";
import { vantageApi } from "./api/client";
import type { ApiError, Asset, DayStop, Home as HomeType, Inspection, Organization, ReportSummary, Room, RoomType, UserSession } from "./types";

type View = "day"|"properties"|"property"|"onboarding"|"review"|"turnover"|"twin"|"reports"|"profile";
export function VantageProduct() {
 const [session,setSession]=useState<UserSession|null>(null),[checking,setChecking]=useState(true),[view,setView]=useState<View>("day"),[homes,setHomes]=useState<HomeType[]>([]),[stops,setStops]=useState<DayStop[]>([]),[reports,setReports]=useState<ReportSummary[]>([]),[home,setHome]=useState<HomeType>(),[inspection,setInspection]=useState<Inspection>(),[roomTypes,setRoomTypes]=useState<RoomType[]>([]),[error,setError]=useState<ApiError|null>(null),[offline,setOffline]=useState(!navigator.onLine);
 useEffect(()=>{vantageApi.me().then(r=>{if(r.ok)setSession(r.data);setChecking(false)}); const on=()=>setOffline(!navigator.onLine);addEventListener("online",on);addEventListener("offline",on);return()=>{removeEventListener("online",on);removeEventListener("offline",on)}},[]);
 const load=useCallback(async()=>{setError(null);const [h,d,r,t]=await Promise.all([vantageApi.homes(),vantageApi.day(),vantageApi.reports(),vantageApi.roomTypes()]);if(h.ok)setHomes(h.data);else setError(h.error);if(d.ok)setStops(d.data);if(r.ok)setReports(r.data);if(t.ok)setRoomTypes(t.data)},[]);
 useEffect(()=>{if(session?.activeOrganizationId)void load()},[session?.activeOrganizationId,load]);
 if(checking)return <div className="v-app"><PageState kind="loading" title="Opening Vantage" detail="Verifying your secure session."/></div>;
 if(!session)return <MagicCodeSignIn onAuthenticated={setSession}/>;
 if(!session.activeOrganizationId)return <OrganizationChooser organizations={session.organizations} onChoose={async(org:Organization)=>{const r=await vantageApi.chooseOrganization(org.id);if(r.ok)setSession({...session,activeOrganizationId:org.id});else setError(r.error)}}/>;
 async function start(type:Inspection["type"]){if(!home)return;const clientId=crypto.randomUUID(),r=await vantageApi.createInspection(home.id,type,clientId);if(!r.ok)return setError(r.error);setInspection(r.data);setView(type==="onboarding"?"onboarding":"turnover")}
 async function createRoom(v:{clientId:string;name:string;roomTypeId:string;floorArea?:string}){if(!inspection)return;const r=await vantageApi.createRoom(inspection.home.id,inspection.id,v);if(r.ok)setInspection({...inspection,rooms:[...inspection.rooms,r.data]});else setError(r.error)}
 async function createAsset(room:Room,v:Partial<Asset>&{clientId:string;type:string;name:string}){if(!inspection)return;const r=await vantageApi.createAsset(room.id,inspection.id,{clientId:v.clientId,type:v.type,name:v.name,locationDetail:v.locationDetail});if(r.ok)setInspection({...inspection,rooms:inspection.rooms.map(x=>x.id===room.id?{...x,assets:[...x.assets,r.data]}:x)});else setError(r.error)}
 const content = view==="day"?<MyDay stops={stops} onOpen={s=>{setHome(s.home);setView("property")}} onProperties={()=>setView("properties")}/>:view==="properties"?<Properties homes={homes} onOpen={h=>{setHome(h);setView("property")}}/>:view==="property"&&home?<PropertySheet home={home} onStart={start} onTwin={()=>setView("twin")}/>:view==="onboarding"&&inspection?<OnboardingCanvas inspection={inspection} roomTypes={roomTypes} offline={offline} error={error} onCreateRoom={createRoom} onCreateAsset={createAsset} onReview={()=>setView("review")}/>:view==="review"&&inspection?<InventoryReview inspection={inspection} error={error} onBack={()=>setView("onboarding")} onComplete={async()=>{const r=await vantageApi.completeInspection(inspection.id,crypto.randomUUID());if(r.ok){setInspection(r.data);setView("twin")}else setError(r.error)}}/>:view==="turnover"&&home?<TurnoverConsole home={home} rooms={inspection?.rooms}/>:view==="twin"&&home?<DigitalTwin home={home} rooms={inspection?.rooms??[]}/>:view==="reports"?<Reports reports={reports}/>:<Profile name={session.name} email={session.email} role={session.organizations.find(o=>o.id===session.activeOrganizationId)?.role??"member"} onLogout={async()=>{await vantageApi.logout();setSession(null)}}/>;
 return <div className="v-app">{error&&view!=="onboarding"&&<div className="v-global-error" role="alert">{error.message}</div>}{content}<nav className="v-nav" aria-label="Primary"><button className={view==="day"?"active":""} onClick={()=>setView("day")}><ClipboardList/><span>My Day</span></button><button className={["properties","property","twin","onboarding","review","turnover"].includes(view)?"active":""} onClick={()=>setView("properties")}><Building2/><span>Properties</span></button><button className={view==="reports"?"active":""} onClick={()=>setView("reports")}><FileText/><span>Reports</span></button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}><UserRound/><span>Profile</span></button></nav></div>
}
