import { useState, type FormEvent } from "react";
import { ArrowRight, Building2, Mail, ShieldCheck } from "lucide-react";
import { ErrorNotice } from "../components";
import { vantageApi } from "../api/client";
import type { ApiError, Organization, UserSession } from "../types";

export function MagicCodeSignIn({ onAuthenticated }: { onAuthenticated: (session: UserSession) => void }) {
  const [step, setStep] = useState<"email" | "code">("email"), [email, setEmail] = useState(""), [code, setCode] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(null); const result = step === "email" ? await vantageApi.requestCode(email.trim()) : await vantageApi.verifyCode(email.trim(), code.replace(/\D/g, "")); setBusy(false); if (!result.ok) return setError(result.error); if (step === "email") setStep("code"); else onAuthenticated(result.data as UserSession); }
  return <main className="v-auth"><section className="v-auth__brand"><span className="v-monogram">V</span><p>Vantage AI</p><h1>The home,<br/><em>understood.</em></h1><p>Field intelligence for homes cared for with intention.</p></section><section className="v-auth__form"><form onSubmit={submit}><p className="v-kicker">Secure field access</p><h2>{step === "email" ? "Welcome back" : "Check your email"}</h2><p>{step === "email" ? "We’ll send a single-use code. No password to remember." : <>Enter the code sent to <strong>{email}</strong>.</>}</p><ErrorNotice error={error}/>{step === "email" ? <label>Email address<div className="v-input-icon"><Mail/><input autoFocus required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></div></label> : <label>Verification code<input className="v-code" autoFocus required inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} aria-describedby="code-help"/><small id="code-help">Six digits · expires shortly</small></label>}<button className="v-button v-button--primary" disabled={busy || (step === "code" && code.length < 6)}>{busy ? "Contacting Vantage…" : step === "email" ? "Send secure code" : "Verify and continue"}<ArrowRight/></button>{step === "code" && <button type="button" className="v-link" onClick={()=>{setStep("email");setCode("");}}>Use a different email</button>}<p className="v-auth__trust"><ShieldCheck/>Encrypted session · Tenant-scoped access</p></form></section></main>;
}

export function OrganizationChooser({ organizations, onChoose }: { organizations: Organization[]; onChoose: (org: Organization) => Promise<void> | void }) {
  const [busy, setBusy] = useState<string>(); return <main className="v-chooser"><header><span className="v-monogram">V</span><p className="v-kicker">Vantage AI</p><h1>Choose your workspace</h1><p>Your role and access are scoped to the organization you select.</p></header><div className="v-org-list">{organizations.map(o=><button key={o.id} disabled={!!busy} onClick={async()=>{setBusy(o.id);await onChoose(o);setBusy(undefined);}}><span><Building2/></span><div><strong>{o.name}</strong><small>{o.role.replaceAll("_", " ")}</small></div><ArrowRight/></button>)}</div></main>;
}
