import { ArrowRight, CalendarDays, ChevronRight, ClipboardCheck, MapPin, Navigation, Plus, TriangleAlert } from "lucide-react";
import { PageState, ScreenHeader } from "../components";
import type { DayStop, Home } from "../types";

export function MyDay({ stops, loading, onOpen, onProperties }: { stops: DayStop[]; loading?: boolean; onOpen: (stop: DayStop)=>void; onProperties?:()=>void }) {
  return <main className="v-page"><ScreenHeader eyebrow="Field plan · Today" title="My Day" action={<span className="v-date"><CalendarDays/>Today</span>}/>{loading ? <PageState kind="loading" title="Loading your route" detail="Checking assignments and current field status."/> : stops.length === 0 ? <PageState kind="empty" title="No assigned stops" detail="There are no live field assignments for your active organization."/> : <><section className="v-mission"><p className="v-kicker">Mission brief</p><h2>{stops.length} {stops.length === 1 ? "home" : "homes"} on today’s route</h2><p>Work syncs continuously. Originals stay on this device until upload is verified.</p></section><ol className="v-stop-list">{stops.map((s,i)=><li key={s.id}><button onClick={()=>onOpen(s)}><span className="v-stop-index">{String(i+1).padStart(2,"0")}</span><div className="v-stop-main"><small>{s.timeLabel ?? s.stage}</small><h3>{s.home.name}</h3><p><MapPin/>{s.home.address}</p>{s.exception && <span className="v-exception"><TriangleAlert/>{s.exception}</span>}</div><div className="v-stop-progress"><strong>{s.progress ? `${s.progress.complete}/${s.progress.total}` : s.stage}</strong><small>{s.progress ? "checks" : "stage"}</small><ChevronRight/></div></button></li>)}</ol></>}<button className="v-fab" onClick={onProperties}><Plus/><span>Open property</span></button></main>;
}

export function Properties({ homes, onOpen }: { homes: Home[]; onOpen:(home:Home)=>void }) { return <main className="v-page"><ScreenHeader eyebrow="Portfolio inventory" title="Properties"/>{homes.length === 0 ? <PageState kind="empty" title="No accessible homes" detail="Homes appear here only when your organization grants access."/> : <div className="v-property-list">{homes.map(h=><button key={h.id} onClick={()=>onOpen(h)}><div className="v-property-code">{h.unitCode}</div><div><p className="v-kicker">{h.cluster ?? "Property"}</p><h2>{h.name}</h2><p><MapPin/>{h.address}</p><small>{h.roomCount ?? 0} rooms · {h.assetCount ?? 0} assets</small></div><ArrowRight/></button>)}</div>}</main> }

export function PropertySheet({ home, onStart, onResume, onTwin }: { home:Home; onStart:(type:"onboarding"|"turnover")=>void; onResume?:()=>void; onTwin?:()=>void }) { return <main className="v-page"><section className="v-property-hero"><p className="v-kicker">{home.unitCode} · {home.cluster ?? "Home"}</p><h1>{home.name}</h1><p><MapPin/>{home.address}</p><button className="v-button v-button--quiet"><Navigation/>Directions</button></section><section className="v-sheet"><div className="v-inventory-line"><span><strong>{home.roomCount ?? 0}</strong> Rooms</span><span><strong>{home.assetCount ?? 0}</strong> Assets</span><button onClick={onTwin}>Open digital twin <ArrowRight/></button></div><h2>Start field work</h2>{home.onboardingStatus === "draft" && <button className="v-launch v-launch--gold" onClick={onResume}><span><ClipboardCheck/><i>In progress</i></span><div><strong>Resume onboarding</strong><small>Continue the saved room and asset inventory</small></div><ChevronRight/></button>}<button className="v-launch" onClick={()=>onStart("onboarding")}><span><Plus/></span><div><strong>New onboarding assessment</strong><small>Build or update the structured home inventory</small></div><ChevronRight/></button><button className="v-launch" onClick={()=>onStart("turnover")}><span><ClipboardCheck/></span><div><strong>Turnover inspection</strong><small>Run the room-oriented readiness checklist</small></div><ChevronRight/></button></section></main> }
