import { AlertTriangle, ArrowLeftRight, Camera, Check, ChevronDown, FileText, LockKeyhole, Shield, UserRound, Wrench } from "lucide-react";
import { PageState, ScreenHeader } from "../components";
import type { Home, ReportSummary, Room } from "../types";

const CHECKS = ["Hot tub","Kitchen","Bathrooms","Bedrooms","Home overall","Outdoors","Utilities","Gifts & summary"];
export function TurnoverConsole({ home, rooms = [] }: { home:Home; rooms?:Room[] }) { return <main className="v-page"><ScreenHeader eyebrow="Turnover inspection" title={home.name}/><section className="v-turnover-summary"><p className="v-kicker">Readiness console</p><h2>0 of 38 checks reviewed</h2><div><span style={{width:"0%"}}/></div><p>No result is assumed. Review each checkpoint and approve captured evidence.</p></section><div className="v-check-sections">{CHECKS.map((name,i)=><details key={name}><summary><span>{String(i+1).padStart(2,"0")}</span><div><small>{rooms[i]?.name ?? "Whole home"}</small><strong>{name}</strong></div><b>0 reviewed</b><ChevronDown/></summary><div className="v-check-empty"><Camera/><p>Open this section to begin verified checks. PASS, FAIL, or NA must be selected explicitly.</p><button className="v-button v-button--quiet">Begin section</button></div></details>)}</div></main> }
export function DigitalTwin({home,rooms}:{home:Home;rooms:Room[]}) { return <main className="v-page"><ScreenHeader eyebrow={`${home.unitCode} · Digital twin`} title={home.name}/><section className="v-twin-hero"><p>The living record</p><strong>{rooms.length}</strong><span>structured rooms</span><strong>{rooms.reduce((n,r)=>n+r.assets.length,0)}</strong><span>tracked assets</span></section>{rooms.length===0?<PageState kind="empty" title="No inventory yet" detail="Complete an onboarding assessment to establish rooms, assets, and originals."/>:<div className="v-twin-rooms">{rooms.map(r=><section key={r.id}><header><div><small>{r.roomType.name}</small><h2>{r.name}</h2></div><span>{r.assets.length}</span></header>{r.assets.map(a=><p key={a.id}>{a.name}<small>{a.type}</small></p>)}</section>)}</div>}</main> }
export function Comparison({home}:{home:Home}) { return <main className="v-page"><ScreenHeader eyebrow="Evidence comparison" title={home.name}/><section className="v-compare-empty"><ArrowLeftRight/><h2>No comparison selected</h2><p>Choose a completed baseline and current inspection to review original evidence side by side. Derived views never replace retained originals.</p><button className="v-button v-button--primary">Choose inspections</button></section></main> }
export function Reports({reports}:{reports:ReportSummary[]}) { return <main className="v-page"><ScreenHeader eyebrow="Verified field records" title="Reports"/>{reports.length===0?<PageState kind="empty" title="No reports available" detail="Completed and authorized inspection reports will appear here."/>:<div className="v-report-list">{reports.map(r=><button key={r.id}><FileText/><div><small>{r.kind} report</small><h2>{r.homeName}</h2><p>{new Date(r.createdAt).toLocaleDateString()}</p></div><span className={`v-report-status v-report-status--${r.status}`}>{r.status}</span></button>)}</div>}</main> }
export function Profile({name,email,role,onLogout}:{name?:string;email:string;role:string;onLogout:()=>void}) { return <main className="v-page"><ScreenHeader eyebrow="Account & administration" title="Profile"/><section className="v-profile-card"><span><UserRound/></span><h2>{name||email}</h2><p>{email}</p><small>{role.replaceAll("_"," ")}</small></section><div className="v-settings"><button><Shield/><span><strong>Organization & access</strong><small>Memberships, roles and home grants</small></span></button><button><Wrench/><span><strong>Integrations</strong><small>Gmail, Slack and Escapia status</small></span></button><button><LockKeyhole/><span><strong>Evidence & audit</strong><small>Retention, legal holds and access history</small></span></button></div><button className="v-button v-button--danger" onClick={onLogout}>Sign out</button></main> }
